language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update
  - sudo locale-gen en_US en_US.UTF-8
  - sudo dpkg-reconfigure locales
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      sudo apt-get install php5-intl
    elif [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      sudo apt-get install php7.0-intl
    elif [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      sudo apt-get install php7.1-intl
    elif [ $TRAVIS_PHP_VERSION = '7.2' ]; then
      sudo apt-get install php7.2-intl
    fi

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      travis_retry wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      php coveralls.phar -v
    fi